## Data Frame - Enrichissement du dictionnaire de Buchanan 1757

### 1 - Ajout d'une une colonne motVedette (transformation/simplification de la prononciation d'origine) en utilisant le mapping du fichier Buchanan_PronChar_counts.csv

#### Import des données

In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

# préciser le chemin du fichier à lire
cheminDuFichierCSV1 = "./../data/dictionary/1757_Buchanan-J.csv" 

# demander à pandas de lire le fichier et garder ce tableau accessible dans une variable
dfDicoBuch = pd.read_csv(cheminDuFichierCSV1, delimiter=";", encoding="utf8")

# afficher à l'écran un échantillon du tableau
dfDicoBuch.sample(n=5)

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId
8755,2,mŏnteʹt,NaN,NaN,NaN,n.,16.0,143
12301,1,sĕdge,NaN,NaN,NaN,n.,56.0,192
6155,1,heath,NaN,NaN,NaN,v.,30.0,105
2967,2,cō_u_rfer,NaN,nbSyll>1 et pas d'accent tonic,NaN,n.,60.0,60
27,5,ăbjūrāʹtion,L.,NaN,NaN,n.,29.0,19

In [3]:
# préciser le chemin du fichier à lire
cheminDuFichierCSV2 = "./../data/dictionary/Buchanan_PronChar_counts.csv" 

# demander à pandas de lire le fichier et garder ce tableau accessible dans une variable
dfPronCharCountBuch = pd.read_csv(cheminDuFichierCSV2, delimiter=";", encoding="utf8")

# afficher à l'écran un échantillon du tableau
dfPronCharCountBuch.sample(n=5)

   char   occ graph
64    ô     4     o
5     u  1623     u
20    ĕ  4262     e
10    ſ  4329     s
13    ā  2079     a

#### Transformation de la prononciation en mot

In [4]:
def motVedette(mot):
    cheminDuFichierCSV = "./../data/dictionary/Buchanan_PronChar_counts.csv"
    pronchar = pd.read_csv(cheminDuFichierCSV, delimiter=";", encoding="utf8")
    TruePron = []
    transfo = ''
    for lettre in mot:
        if (pronchar[pronchar['char']== lettre]['graph'].isnull().values[0]):
            transfo = ''
        else: transfo = pronchar[pronchar['char']== lettre]['graph'].values[0]
        TruePron.append(transfo)
    TruePron = ''.join(TruePron)
    return TruePron

In [5]:
# appeler cette fonction sur toutes les lignes de la matrice pour remplir une nouvelle colonne grace à apply
dfDicoBuch['motVedette'] = dfDicoBuch.apply(lambda x: motVedette(x['pron']),1)

dfDicoBuch

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned
...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica

In [7]:
cheminDicoBuchMot = "./../data/dictionary/DicoMotVedette.csv"
dfDicoBuch.to_csv(cheminDicoBuchMot, sep=";", encoding="utf8", index=False )

### 2) Ajouter une colonne Sampa et une colonne Ipa à partir des mots vedettes obtenus (transformation/croisement de données) en utilisant ./../data/dataframe/BigiRichSample.csv

In [9]:
pathDicoBigiRich = "./../data/dataframe/BigiRich.csv"
dfDicoBigiRich = pd.read_csv(pathDicoBigiRich, delimiter=";", encoding="utf8")

In [10]:
dfDicoBigiRich.sample(n=10)

                 hwd            pronSampa         ipa
94302        quito's        k w i: 4 @U z    kwiːɾoʊz
28152    deciphering   d @ s aI f 3:r i N  dəs?fɜ:riŋ
55892         hustle            h V s @ l       hʌsəl
70218         lucken            l V k @ n       lʌkən
45638      gentility  dZ E n t I l i 4 i:  ?ɛntɪliɾiː
7516            bali             b A l i:       bɑliː
34574   earthquake's     3:r T k w eI k s   ɜ:rθkw?ks
8902           bayul             b eI @ l        b?əl
64878         kruger         k r\ u g 3:r     kɹugɜ:r
118865       torstar     t O: r\ s t A r\    tOːɹstɑɹ

In [12]:
dfDicoBuch_final = dfDicoBuch.merge(dfDicoBigiRich, left_on = ['motVedette'], right_on= ['hwd']).drop(columns=['motVedette'])
dfDicoBuch_final

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,hwd,pronSampa,ipa
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus,{ b @ k @ s,æbəkəs
1,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon,@ b { n d @ n,əbændən
2,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned,@ b { n d @ n d,əbændənd
3,2,ăbăʹſh,F.,NaN,NaN,v.,9.0,19,abash,@ b { S,əbæʃ
4,2,ăbāʹte,F.,NaN,NaN,v.,10.0,19,abate,@ b eI t,əb?t
...,...,...,...,...,...,...,...,...,...,...,...
10328,2,zĕʹnith,NaN,NaN,NaN,n.,11.0,241,zenith,z i: n @ T,ziːnəθ
10329,1,zĕſt,NaN,NaN,NaN,n.,13.0,241,zest,z E s t,zɛst
10330,1,zĭnk,NaN,NaN,NaN,n.,14.0,241,zink,z I N k,zɪŋk
10331,3,zōʹdĭac,NaN,NaN,NaN,n.,16.0,241,zodiac,z @U 4 i: { k,zoʊɾiːæk
10332,1,zōne,NaN,NaN,NaN,n.,18.0,241,zone,z @U n,zoʊn

In [13]:
dfDicoBuch_final = dfDicoBuch_final.rename(columns={'hwd': 'Mot'})
dfDicoBuch_final

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,Mot,pronSampa,ipa
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus,{ b @ k @ s,æbəkəs
1,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon,@ b { n d @ n,əbændən
2,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned,@ b { n d @ n d,əbændənd
3,2,ăbăʹſh,F.,NaN,NaN,v.,9.0,19,abash,@ b { S,əbæʃ
4,2,ăbāʹte,F.,NaN,NaN,v.,10.0,19,abate,@ b eI t,əb?t
...,...,...,...,...,...,...,...,...,...,...,...
10328,2,zĕʹnith,NaN,NaN,NaN,n.,11.0,241,zenith,z i: n @ T,ziːnəθ
10329,1,zĕſt,NaN,NaN,NaN,n.,13.0,241,zest,z E s t,zɛst
10330,1,zĭnk,NaN,NaN,NaN,n.,14.0,241,zink,z I N k,zɪŋk
10331,3,zōʹdĭac,NaN,NaN,NaN,n.,16.0,241,zodiac,z @U 4 i: { k,zoʊɾiːæk
10332,1,zōne,NaN,NaN,NaN,n.,18.0,241,zone,z @U n,zoʊn

In [14]:
dfDicoBuch_final['Mot'].value_counts()

joint       2
subject     2
project     2
bush        2
canvass     2
           ..
motto       1
confine     1
ductile     1
renewal     1
flexible    1
Name: Mot, Length: 10317, dtype: int64

#### Isoler les mots de Buchanan qui n'existent pas dans Bigi. Tenter de comprendre les différentes causes et tenter d'expliquer comment résoudre les différents problèmes (bonus)

In [19]:
mots_manquants = [x for x in list(dfDicoBuch['motVedette']) if x not in list(dfDicoBuch_final['Mot'])]
#mots_manquants

In [20]:
# Il y a une différence de 15 800 - 10 333 mots manquants entre nos deux sources de données
len(mots_manquants)

5467

Les mots de Buchanan n'existant pas dans Bigi sont potentiellement des mots qui n'ont pas été reconnus à partir de leur prononciation. Cela est surement du à notre table de mapping que nous avons eu à notre disposition en début de processus pour récupérer les caractéres spécifique à une prononciation donnée. Certains caractères ont du être omis ou mal renseignés pour une prononciation donnée.

Pour résoudre ce problème, nous pourrions calculer un indicateur pour qualifier une distance entre des mots ou des groupes de mots. Et donc de définir quel mot de Bigi est le plus adapté pour un mot donné de Buchanan. Après avoir fait des recherches sur internet, la distance de Hamming, Levenshtein ou Stoilos sont des bons exemples d'indicateurs.Ils évalueraient les distances entre les mots de nos deux data frame. La distance **la plus faible** est celle qui sera choisie pour obtenir le mot le plus pertinent. Cette association sera dès lors **automatisée** par l'intermédiaire d'une fonction "distance" qui sera codée et appellée dans le processus. Les résultats obtenus seront stockés dans un autre data frame.

### 3) sauvegarder la nouvelle matrice obtenue dans ./../data/dataframe/BuchananRich.csv

In [22]:
cheminDuDfFinal = "./../data/dataframe/BuchananRich.csv"

dfDicoBuch_final.to_csv(cheminDuDfFinal, sep=";", encoding="utf8", index=False )